VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "saucy64-phalcon"
  config.vm.box_url = "http://my.laurent.lab.easyflirt.com/boxes/saucy64-phalcon.box"

  config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 3306, host: 13306

  config.vm.synced_folder "./project", "/var/www"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

end

