VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "debian-webdev"
  config.vm.box_url = "http://is.gd/debian73box"

  config.vm.network :forwarded_port, guest: 80, host: 8080
  
  config.vm.synced_folder "./webroot", "/usr/share/nginx/html/demo"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision/ansible-playbook.yml"
    ansible.sudo = true
  end

end
