<h5>Formulaire Ajouter</h5>

<?php echo $this->tag->form('demo/add'); ?>

nom : <?php echo $this->tag->textField(array('lastname')); ?><br />
Prénom : <?php echo $this->tag->textField(array('firstname')); ?><br />
<br />
<?php echo $this->tag->submitButton('add'); ?>

<?php echo $this->tag->endForm(); ?>

<?php if (isset($form_errors)): ?>
	Désolé, nous avons rencontré les problèmes suivants durant l'enregistrement de votre formulaire :
	<ul>
	<?php foreach ($form_errors as $message): ?>
		<li><?php echo $message->getMessage(); ?></li>
	<?php endforeach; ?>
	</ul>
<?php endif; ?>

